// <auto-generated />
using API_Senior.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_Senior.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("API_Senior.Data.Ponto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.Property<int>("employerId")
                        .HasColumnType("int");

                    b.Property<string>("includedAt")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Pontos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            employeeId = 83,
                            employerId = 111,
                            includedAt = "2022-03-15 16:30:00"
                        },
                        new
                        {
                            Id = 2,
                            employeeId = 95,
                            employerId = 111,
                            includedAt = "2022-03-15 16:33:00"
                        },
                        new
                        {
                            Id = 3,
                            employeeId = 103,
                            employerId = 111,
                            includedAt = "2022-03-15 16:32:00"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
